#ifndef QRCODEPICKER_GLOBAL_H
#define QRCODEPICKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QRCODEPICKER_LIBRARY)
#  define QRCODEPICKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QRCODEPICKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QRCODEPICKER_GLOBAL_H
